sonar.projectKey=projet_Tkinter

sonar.projectName=projet_Tkinter

sonar.host.url=http://localhost:9000

sonar.token=sqp_1524f19b196fd8490ee34ee9fdf51c03f7cafa1c

sonar.sources=.


sonar.sourceEncoding=UTF-8